name: Deploy Dev Environment

on:
  # Runs on all pushes to repository
  push:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}

      # Dynamically creates appsettings.secrets.json file on the fly for the build
      - name: Create appsettings.secrets File
        run: |
          echo "{
            \"connectionstrings\": {
              \"_msg\": \"add any necessary connection string names here, put the strings themselves in appsettings.secrets.json\",
              \"dotnet-react-db\": \"${{ secrets.AZURE_SQL_CONNECTION_STRING_DEV }}\",
              \"dotnet-react-db.dev\": \"${{ secrets.AZURE_SQL_CONNECTION_STRING_DEV }}\"
            }
          }" > CapstoneApp.Host/appsettings.secrets.json

      - name: Log in to ACR via Azure CLI
        run: |
          az acr login --name dotnetreactacr

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: dotnetreactacr.azurecr.io/dotnet-react-app:${{ github.sha }}

      - name: Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: dotnet-react-dev
          resourceGroup: rg-dotnet-react-dev
          imageToDeploy: dotnetreactacr.azurecr.io/dotnet-react-app:${{ github.sha }}
          acrName: dotnetreactacr
          acrUsername: dotnetreactacr
          acrPassword: ${{ secrets.ACR_PASSWORD }}