name: Deploy Production Environment

on:
  # Runs on main with Github Release
  release:
    types: [published]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_PROD }}

      - name: Create appsettings.secrets File
        run: |
          echo "{
            \"connectionstrings\": {
              \"_msg\": \"add any necessary connection string names here, put the strings themselves in appsettings.secrets.json\",
              \"dotnet-react-db\": \"${{ secrets.AZURE_SQL_CONNECTION_STRING_PROD }}\",
              \"dotnet-react-db.prod\": \"${{ secrets.AZURE_SQL_CONNECTION_STRING_PROD }}\"
            }
          }" > CapstoneApp.Host/appsettings.secrets.json

      - name: Log in to ACR via Azure CLI
        run: |
          az acr login --name dotnetreactacr

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: dotnetreactacr.azurecr.io/dotnet-react-app:prod-${{ github.sha }}

      - name: Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: dotnet-react-prod
          resourceGroup: rg-dotnet-react-shared
          imageToDeploy: dotnetreactacr.azurecr.io/dotnet-react-app:${{ github.sha }}
          acrName: dotnetreactacr
          acrUsername: dotnetreactacr
          acrPassword: ${{ secrets.ACR_PASSWORD }}
          containerAppEnvironment: ${{ vars.CONTAINER_APP_ENVIRONMENT }}